In [2]:
base_url = "https://data.cms.gov/data-api/v1/dataset/6c63099b-0794-40a0-925c-51a66b9b9901/data"

## Sending GET Request

In [3]:
import requests

In [4]:
all_data = []
size = 5000
offset = 0

while True:
    params = {
        "size" : size,
        "offset": offset
    }
    response = requests.get(base_url, params=params)
    data=response.json()

    if not data:
        break

    all_data.extend(data)
    offset += size

import pandas as pd
home_health_raw=pd.DataFrame(all_data)

## Investigating Response

In [5]:
response.status_code

200

In [6]:
type(data)

list

## Pandas

In [7]:
import pandas as pd
home_health_raw=pd.DataFrame(all_data)

In [8]:
#reports 1000 rows and 33 columns, so not al the rows needed
home_health_raw.shape

(124399, 33)

In [9]:
home_health_raw.columns

Index(['YEAR', 'YEAR_TYPE', 'SMRY_CTGRY', 'SRVC_CTGRY', 'STATE', 'PRVDR_ID',
       'PRVDR_NAME', 'PRVDR_CITY', 'PRVDR_ZIP', 'GRPNG', 'GRPNG_DESC',
       'BENE_DSTNCT_CNT', 'TOT_EPSD_STAY_CNT', 'TOT_SRVC_DAYS',
       'AVG_CHRG_PER_BENE', 'AVG_ALOWD_AMT_PER_BENE', 'AVG_PYMT_AMT_PER_BENE',
       'AVG_STDZD_PYMT_AMT_PER_BENE', 'AVG_CHRG_PER_EPSD',
       'AVG_ALOWD_AMT_PER_EPSD', 'AVG_PYMT_AMT_PER_EPSD',
       'AVG_STDZD_PYMT_AMT_PER_EPSD', 'AVG_CHRG_PER_DAY',
       'AVG_ALOWD_AMT_PER_DAY', 'AVG_PYMT_AMT_PER_DAY',
       'AVG_STDZD_PYMT_AMT_PER_DAY', 'PT_VISITS_CNT', 'OT_VISITS_CNT',
       'SLP_VISITS_CNT', 'CASEMIX_SRC_TMNG', 'CASEMIX_SRC_TMNG_EPSD_PCT',
       'CASEMIX_CMRBDTY', 'CASEMIX_CMRBDTY_EPSD_PCT'],
      dtype='object')

In [10]:
home_health_raw.head()

,YEAR,YEAR_TYPE,SMRY_CTGRY,SRVC_CTGRY,STATE,PRVDR_ID,PRVDR_NAME,PRVDR_CITY,PRVDR_ZIP,GRPNG,...,AVG_ALOWD_AMT_PER_DAY,AVG_PYMT_AMT_PER_DAY,AVG_STDZD_PYMT_AMT_PER_DAY,PT_VISITS_CNT,OT_VISITS_CNT,SLP_VISITS_CNT,CASEMIX_SRC_TMNG,CASEMIX_SRC_TMNG_EPSD_PCT,CASEMIX_CMRBDTY,CASEMIX_CMRBDTY_EPSD_PCT
0,2024,CY,NATION,HH,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,1AA11,...,267,267,256,22172589,5956458,1055632,CMNTY_ERLY,11,NO,29
1,2024,CY,NATION,HH,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,1AA21,...,272,272,270,22172589,5956458,1055632,CMNTY_ERLY,11,LOW,55
2,2024,CY,NATION,HH,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,1AA31,...,294,294,291,22172589,5956458,1055632,CMNTY_ERLY,11,HIGH,15
3,2024,CY,NATION,HH,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,1AB11,...,266,266,263,22172589,5956458,1055632,CMNTY_ERLY,11,NO,29
4,2024,CY,NATION,HH,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,NATIONAL TOTAL,1AB21,...,272,272,275,22172589,5956458,1055632,CMNTY_ERLY,11,LOW,55

In [11]:
home_health_raw["YEAR"].unique()

array(['2024'], dtype=object)

In [12]:
home_health_raw["SMRY_CTGRY"].value_counts()

SMRY_CTGRY
PROVIDER    106381
STATE        17586
NATION         432
Name: count, dtype: int64

In [13]:
home_health_raw["TOT_EPSD_STAY_CNT"].value_counts()

TOT_EPSD_STAY_CNT
11      5247
12      5231
13      4811
14      4667
15      4559
        ...
2576       1
1970       1
1909       1
1683       1
917        1
Name: count, Length: 2496, dtype: int64

In [14]:
home_health_raw.to_csv("home_health_raw_data.csv", index=False)

## IMPORTING CLEANED DATA FROM EXCEL AS CSV

In [15]:
home_health = pd.read_csv("home_health_clean.csv")

/var/folders/m_/fl3h0s5n4d9ds8g7mp3b3j780000gn/T/ipykernel_79899/21616042.py:1: DtypeWarning: Columns (5,8) have mixed types. Specify dtype option on import or set low_memory=False.
  home_health = pd.read_csv("home_health_clean.csv")

In [16]:
home_health.iloc[:,[5,8]].head(5)

         PRVDR_ID       PRVDR_ZIP
0  NATIONAL TOTAL  NATIONAL TOTAL
1  NATIONAL TOTAL  NATIONAL TOTAL
2  NATIONAL TOTAL  NATIONAL TOTAL
3  NATIONAL TOTAL  NATIONAL TOTAL
4  NATIONAL TOTAL  NATIONAL TOTAL

In [17]:
home_health.dtypes

YEAR                            int64
YEAR_TYPE                      object
SMRY_CTGRY                     object
SRVC_CTGRY                     object
STATE                          object
PRVDR_ID                       object
PRVDR_NAME                     object
PRVDR_CITY                     object
PRVDR_ZIP                      object
GRPNG                          object
GRPNG_DESC                     object
BENE_DSTNCT_CNT                 int64
TOT_EPSD_STAY_CNT               int64
TOT_SRVC_DAYS                   int64
AVG_CHRG_PER_BENE               int64
AVG_ALOWD_AMT_PER_BENE          int64
AVG_PYMT_AMT_PER_BENE           int64
AVG_STDZD_PYMT_AMT_PER_BENE     int64
AVG_CHRG_PER_EPSD               int64
AVG_ALOWD_AMT_PER_EPSD          int64
AVG_PYMT_AMT_PER_EPSD           int64
AVG_STDZD_PYMT_AMT_PER_EPSD     int64
AVG_CHRG_PER_DAY                int64
AVG_ALOWD_AMT_PER_DAY           int64
AVG_PYMT_AMT_PER_DAY            int64
AVG_STDZD_PYMT_AMT_PER_DAY      int64
PT_VISITS_CNT                   int64
OT_VISITS_CNT                   int64
SLP_VISITS_CNT                  int64
CASEMIX_SRC_TMNG               object
CASEMIX_SRC_TMNG_EPSD_PCT       int64
CASEMIX_CMRBDTY                object
CASEMIX_CMRBDTY_EPSD_PCT        int64
dtype: object

In [18]:
home_health.isnull().sum()

YEAR                           0
YEAR_TYPE                      0
SMRY_CTGRY                     0
SRVC_CTGRY                     0
STATE                          0
PRVDR_ID                       0
PRVDR_NAME                     0
PRVDR_CITY                     0
PRVDR_ZIP                      0
GRPNG                          0
GRPNG_DESC                     0
BENE_DSTNCT_CNT                0
TOT_EPSD_STAY_CNT              0
TOT_SRVC_DAYS                  0
AVG_CHRG_PER_BENE              0
AVG_ALOWD_AMT_PER_BENE         0
AVG_PYMT_AMT_PER_BENE          0
AVG_STDZD_PYMT_AMT_PER_BENE    0
AVG_CHRG_PER_EPSD              0
AVG_ALOWD_AMT_PER_EPSD         0
AVG_PYMT_AMT_PER_EPSD          0
AVG_STDZD_PYMT_AMT_PER_EPSD    0
AVG_CHRG_PER_DAY               0
AVG_ALOWD_AMT_PER_DAY          0
AVG_PYMT_AMT_PER_DAY           0
AVG_STDZD_PYMT_AMT_PER_DAY     0
PT_VISITS_CNT                  0
OT_VISITS_CNT                  0
SLP_VISITS_CNT                 0
CASEMIX_SRC_TMNG               0
CASEMIX_SRC_TMNG_EPSD_PCT      0
CASEMIX_CMRBDTY                0
CASEMIX_CMRBDTY_EPSD_PCT       0
dtype: int64

In [19]:
home_health.shape

(124399, 33)

In [20]:
home_health.describe()

,YEAR,BENE_DSTNCT_CNT,TOT_EPSD_STAY_CNT,TOT_SRVC_DAYS,AVG_CHRG_PER_BENE,AVG_ALOWD_AMT_PER_BENE,AVG_PYMT_AMT_PER_BENE,AVG_STDZD_PYMT_AMT_PER_BENE,AVG_CHRG_PER_EPSD,AVG_ALOWD_AMT_PER_EPSD,...,AVG_STDZD_PYMT_AMT_PER_EPSD,AVG_CHRG_PER_DAY,AVG_ALOWD_AMT_PER_DAY,AVG_PYMT_AMT_PER_DAY,AVG_STDZD_PYMT_AMT_PER_DAY,PT_VISITS_CNT,OT_VISITS_CNT,SLP_VISITS_CNT,CASEMIX_SRC_TMNG_EPSD_PCT,CASEMIX_CMRBDTY_EPSD_PCT
count,124399.0,124399.000000,124399.00000,1.243990e+05,1.243990e+05,124399.000000,124399.000000,124399.000000,1.243990e+05,124399.000000,...,124399.000000,124399.000000,124399.000000,124399.000000,124399.000000,1.243990e+05,1.243990e+05,1.243990e+05,124399.000000,124399.000000
mean,2024.0,107.065660,153.30739,1.133243e+03,3.868270e+03,2894.195050,2894.195050,2921.547553,2.927361e+03,2128.611814,...,2150.244198,390.270677,287.864967,287.864975,291.114326,1.583455e+05,4.260174e+04,7.553084e+03,43.193064,44.997460
std,0.0,1314.506108,2111.77917,1.489187e+04,1.113372e+04,1333.740745,1333.740826,1219.919381,1.090960e+04,694.405700,...,601.553000,1293.395045,70.817716,70.817729,54.936661,1.331980e+06,3.552877e+05,6.303313e+04,25.054119,17.145708
min,2024.0,11.000000,11.00000,2.200000e+01,2.940000e+02,718.000000,718.000000,1028.000000,2.400000e+02,543.000000,...,955.000000,43.000000,66.000000,66.000000,71.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,1.000000
25%,2024.0,14.000000,17.00000,1.250000e+02,2.078000e+03,2147.000000,2147.000000,2270.000000,1.537000e+03,1563.000000,...,1643.000000,223.000000,241.000000,241.000000,256.000000,4.218000e+03,9.730000e+02,1.290000e+02,20.000000,27.000000
50%,2024.0,19.000000,27.00000,1.950000e+02,2.934000e+03,2567.000000,2567.000000,2658.000000,2.268000e+03,2089.000000,...,2138.000000,296.000000,277.000000,277.000000,288.000000,8.744000e+03,2.676000e+03,4.610000e+02,46.000000,53.000000
75%,2024.0,35.000000,52.00000,3.740000e+02,4.389000e+03,3191.000000,3191.000000,3123.000000,3.387000e+03,2555.000000,...,2630.000000,437.000000,323.000000,323.000000,322.000000,2.142900e+04,6.987000e+03,1.317000e+03,64.000000,59.000000
max,2024.0,126023.000000,206562.00000,1.257133e+06,3.758241e+06,25839.000000,25839.000000,26715.000000,3.758241e+06,6657.000000,...,5326.000000,443388.000000,955.000000,955.000000,900.000000,2.217259e+07,5.956458e+06,1.055632e+06,98.000000,100.000000

In [21]:
home_health.nunique()

YEAR                               1
YEAR_TYPE                          1
SMRY_CTGRY                         3
SRVC_CTGRY                         1
STATE                             53
PRVDR_ID                        5741
PRVDR_NAME                      4638
PRVDR_CITY                      1938
PRVDR_ZIP                       3210
GRPNG                            432
GRPNG_DESC                       432
BENE_DSTNCT_CNT                 2135
TOT_EPSD_STAY_CNT               2496
TOT_SRVC_DAYS                   6410
AVG_CHRG_PER_BENE              13349
AVG_ALOWD_AMT_PER_BENE          7578
AVG_PYMT_AMT_PER_BENE           7577
AVG_STDZD_PYMT_AMT_PER_BENE     7183
AVG_CHRG_PER_EPSD              10906
AVG_ALOWD_AMT_PER_EPSD          4042
AVG_PYMT_AMT_PER_EPSD           4042
AVG_STDZD_PYMT_AMT_PER_EPSD     2895
AVG_CHRG_PER_DAY                1407
AVG_ALOWD_AMT_PER_DAY            646
AVG_PYMT_AMT_PER_DAY             646
AVG_STDZD_PYMT_AMT_PER_DAY       533
PT_VISITS_CNT                   3942
OT_VISITS_CNT                   2220
SLP_VISITS_CNT                   977
CASEMIX_SRC_TMNG                   4
CASEMIX_SRC_TMNG_EPSD_PCT         98
CASEMIX_CMRBDTY                    3
CASEMIX_CMRBDTY_EPSD_PCT          95
dtype: int64

## Exploratory Data Analysis

In [22]:
home_health.SMRY_CTGRY.value_counts()

SMRY_CTGRY
PROVIDER    106381
STATE        17586
NATION         432
Name: count, dtype: int64

In [23]:
home_health.PRVDR_NAME.nunique()

4638

In [24]:
home_health.PRVDR_NAME.unique()

array(['NATIONAL TOTAL', 'STATE TOTAL', 'Providence Home Health Alaska',
       ..., 'Caringedge Healthcare Of Casper Llc',
       'Rocky Mountain Home Care-green River',
       'Best Home Health & Hospice Llc'], shape=(4638,), dtype=object)

In [25]:
home_health.GRPNG.value_counts()

GRPNG
3EC21    2859
3HA21    2790
3HB21    2703
3HC21    2534
3EB21    2450
         ...
1GB31       4
1DA31       3
4FB31       2
2FA31       2
4FA31       2
Name: count, Length: 432, dtype: int64

In [26]:
home_health.BENE_DSTNCT_CNT.describe()

count    124399.000000
mean        107.065660
std        1314.506108
min          11.000000
25%          14.000000
50%          19.000000
75%          35.000000
max      126023.000000
Name: BENE_DSTNCT_CNT, dtype: float64

In [27]:
home_health.TOT_EPSD_STAY_CNT.describe()

count    124399.00000
mean        153.30739
std        2111.77917
min          11.00000
25%          17.00000
50%          27.00000
75%          52.00000
max      206562.00000
Name: TOT_EPSD_STAY_CNT, dtype: float64

In [28]:
home_health.BENE_DSTNCT_CNT.describe()

count    124399.000000
mean        107.065660
std        1314.506108
min          11.000000
25%          14.000000
50%          19.000000
75%          35.000000
max      126023.000000
Name: BENE_DSTNCT_CNT, dtype: float64

In [29]:
home_health.AVG_CHRG_PER_DAY.describe()

count    124399.000000
mean        390.270677
std        1293.395045
min          43.000000
25%         223.000000
50%         296.000000
75%         437.000000
max      443388.000000
Name: AVG_CHRG_PER_DAY, dtype: float64

In [30]:
home_health.AVG_CHRG_PER_EPSD.describe()

count    1.243990e+05
mean     2.927361e+03
std      1.090960e+04
min      2.400000e+02
25%      1.537000e+03
50%      2.268000e+03
75%      3.387000e+03
max      3.758241e+06
Name: AVG_CHRG_PER_EPSD, dtype: float64

In [31]:
home_health.AVG_CHRG_PER_BENE.describe()

count    1.243990e+05
mean     3.868270e+03
std      1.113372e+04
min      2.940000e+02
25%      2.078000e+03
50%      2.934000e+03
75%      4.389000e+03
max      3.758241e+06
Name: AVG_CHRG_PER_BENE, dtype: float64

In [32]:
home_health.GRPNG_DESC.value_counts()

GRPNG_DESC
Clinical Group and Functional Level: MS Rehab - High; Admission Source and Timing: Late - Community; Comorbidity Adjustment: Single                             2859
Clinical Group and Functional Level: MMTA - Cardiac - Low; Admission Source and Timing: Late - Community; Comorbidity Adjustment: Single                        2790
Clinical Group and Functional Level: MMTA - Cardiac - Medium; Admission Source and Timing: Late - Community; Comorbidity Adjustment: Single                     2703
Clinical Group and Functional Level: MMTA - Cardiac - High; Admission Source and Timing: Late - Community; Comorbidity Adjustment: Single                       2534
Clinical Group and Functional Level: MS Rehab - Medium; Admission Source and Timing: Late - Community; Comorbidity Adjustment: Single                           2450
                                                                                                                                                                ...
Clinical Group and Functional Level: MMTA - Surgical Aftercare - Medium; Admission Source and Timing: Early - Community; Comorbidity Adjustment: Interaction       4
Clinical Group and Functional Level: Complex - Low; Admission Source and Timing: Early - Community; Comorbidity Adjustment: Interaction                            3
Clinical Group and Functional Level: Behavioral Health - Medium; Admission Source and Timing: Late - Institutional; Comorbidity Adjustment: Interaction            2
Clinical Group and Functional Level: Behavioral Health - Low; Admission Source and Timing: Early - Institutional; Comorbidity Adjustment: Interaction              2
Clinical Group and Functional Level: Behavioral Health - Low; Admission Source and Timing: Late - Institutional; Comorbidity Adjustment: Interaction               2
Name: count, Length: 432, dtype: int64

In [33]:
home_health.AVG_PYMT_AMT_PER_BENE.describe()

count    124399.000000
mean       2894.195050
std        1333.740826
min         718.000000
25%        2147.000000
50%        2567.000000
75%        3191.000000
max       25839.000000
Name: AVG_PYMT_AMT_PER_BENE, dtype: float64

In [34]:
home_health.AVG_STDZD_PYMT_AMT_PER_BENE.describe()

count    124399.000000
mean       2921.547553
std        1219.919381
min        1028.000000
25%        2270.000000
50%        2658.000000
75%        3123.000000
max       26715.000000
Name: AVG_STDZD_PYMT_AMT_PER_BENE, dtype: float64

## SQL ANALYSIS

In [35]:
home_health.dtypes

YEAR                            int64
YEAR_TYPE                      object
SMRY_CTGRY                     object
SRVC_CTGRY                     object
STATE                          object
PRVDR_ID                       object
PRVDR_NAME                     object
PRVDR_CITY                     object
PRVDR_ZIP                      object
GRPNG                          object
GRPNG_DESC                     object
BENE_DSTNCT_CNT                 int64
TOT_EPSD_STAY_CNT               int64
TOT_SRVC_DAYS                   int64
AVG_CHRG_PER_BENE               int64
AVG_ALOWD_AMT_PER_BENE          int64
AVG_PYMT_AMT_PER_BENE           int64
AVG_STDZD_PYMT_AMT_PER_BENE     int64
AVG_CHRG_PER_EPSD               int64
AVG_ALOWD_AMT_PER_EPSD          int64
AVG_PYMT_AMT_PER_EPSD           int64
AVG_STDZD_PYMT_AMT_PER_EPSD     int64
AVG_CHRG_PER_DAY                int64
AVG_ALOWD_AMT_PER_DAY           int64
AVG_PYMT_AMT_PER_DAY            int64
AVG_STDZD_PYMT_AMT_PER_DAY      int64
PT_VISITS_CNT                   int64
OT_VISITS_CNT                   int64
SLP_VISITS_CNT                  int64
CASEMIX_SRC_TMNG               object
CASEMIX_SRC_TMNG_EPSD_PCT       int64
CASEMIX_CMRBDTY                object
CASEMIX_CMRBDTY_EPSD_PCT        int64
dtype: object